title       = "opentdb"
baseURL     = "https://opentdb-cli.tamnd.com/"
description = "A command line for opentdb."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/opentdb-cli"
